// Generated by https://quicktype.io

export interface PlanListDto {
    list: PlanDto[];
}

export interface PlanDto {
    name:        string;
    price:       number;
    description: string[];
    age:         number;
}
